pipeline {
    agent any
    stages {
        stage('checkout-git'){
            steps{
                git poll: true, url: 'https://github.com/stevenHenaoSofka/pruebaPipeline.git'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew clean build'
            }
        }
    }
    post {
           success {
               // Archive the built artifacts
               archive includes: 'pkg/*.gem'
           }
           always {
               // publish html
               publishHTML([
                   allowMissing: false,
                   alwaysLinkToLastBuild: false,
                   keepAll: false,
                   reportDir: 'build/jacocoHtml',
                   reportFiles: 'index.html',
                   reportName: 'HTML Report',
                   reportTitles: ''
                   ])
           }
    }


}
